### ISSUE TITLE
DRYing up the Dockerfile.tm* file(s)

### ISSUE THREAD

**Issue by asbjornenge** [asbjornenge/Dockerfile.tmLanguage#7]
I also maintain these files in the [Docker.tmbundle](https://github.com/asbjornenge/Docker.tmbundle) repo. The reason I've kept this repo around is because it's the one added to package control. Would be nice to DRY up this.

As I see it we have two options:
1. Modify package control to point to the Docker.tmbundle repo for the Dockerfile package. Is that possible? Would it work with a tmbundle?
2. Align the files. I'm open to keeping this repo around, but it would be nice if the files were the same. So whenever we need to update something, we can start with Docker.tmbundle and simply copy the .tmLanguage file to this repo. See any challenges with that? Maybe the `uuid` is different, I don't know if it matters.

@princemaple thoughts? ^

I would give everyone with collaborator access here the same in the bundle repo.

**Comment by princemaple** [comment]
Good news, my limited testing suggests that your [tmbundle](https://github.com/asbjornenge/Docker.tmbundle) does work. I directly cloned it into the sublime package folder and it worked.

If I'm not wrong, we can simply ditch this repo, submit the change (just a repo change) to package control channels, and add a converted sublime syntax file into the other repo.

**Comment by asbjornenge** [comment]
@princemaple sounds great :grin: Do you have time to make this happen? I'm a bit swamped with other projects :stuck_out_tongue: I'll add you as a collaborator om `tmbundle` right away :+1:

**Comment by princemaple** [comment]
https://github.com/wbond/package_control_channel/pull/4959

**Comment by asbjornenge** [comment]
@princemaple fantastic :heart_eyes: As soon as it's merged I'll update this README saying deprecated and poiting to tmbundle :point_left:

**Comment by princemaple** [comment]
:+1:

On Wed, Nov 4, 2015 at 9:26 PM, Asbjorn Enge <notifications@github.com>
wrote:

> @princemaple <https://github.com/princemaple> fantastic [image:
> :heart_eyes:] As soon as it's merged I'll update this README saying
> deprecated and poiting to tmbundle [image: :point_left:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asbjornenge/Dockerfile.tmLanguage/issues/7#issuecomment-153673535>
> .
>



-- 
Regards,

Po Chen

**Comment by FichteFoll** [comment]
PR merged

**Comment by princemaple** [comment]
Thanks @FichteFoll !

**Comment by asbjornenge** [comment]
:tada:
